export const dummyItems = [
  {
    sku: "SKU-LAPTOP01",
    name: 'MacBook Pro 16"',
    barcode: "123456789012",
    cost: 1200.0,
    price: 1999.99,
    brand: "Apple",
    category_id: 1,
    minimum_quantity: 5,
    description: "Latest model MacBook Pro with M2 chip",
    is_active: true,
    current_quantity: 0,
  },
  {
    sku: "SKU-PHONE01",
    name: "iPhone 14 Pro",
    barcode: "123456789013",
    cost: 800.0,
    price: 1299.99,
    brand: "Apple",
    category_id: 1,
    minimum_quantity: 8,
    description: "Latest iPhone model with dynamic island",
    is_active: true,
    current_quantity: 0,
  },
  {
    sku: "SKU-WATCH01",
    name: "Apple Watch Series 8",
    barcode: "123456789014",
    cost: 300.0,
    price: 499.99,
    brand: "Apple",
    category_id: 1,
    minimum_quantity: 10,
    description: "Latest Apple Watch with temperature sensing",
    is_active: true,
    current_quantity: 0,
  },
  {
    sku: "SKU-TABLET01",
    name: 'iPad Pro 12.9"',
    barcode: "123456789015",
    cost: 700.0,
    price: 1099.99,
    brand: "Apple",
    category_id: 1,
    minimum_quantity: 4,
    description: "12.9-inch iPad Pro with M2 chip",
    is_active: true,
    current_quantity: 0,
  },
  {
    sku: "SKU-EARBUD01",
    name: "AirPods Pro",
    barcode: "123456789016",
    cost: 150.0,
    price: 249.99,
    brand: "Apple",
    category_id: 1,
    minimum_quantity: 15,
    description: "2nd generation AirPods Pro with noise cancellation",
    is_active: true,
    current_quantity: 0,
  },
]

